import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'

export const dynamic = "force-dynamic";

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="/home" className={styles.card}>
            <h2>Home</h2>
          </a>

          <a href="profile" className={styles.card}>
            <h2>Profile</h2>
          </a>
        </div>

        <b>ENV</b>
        <div className={styles.grid}>
          <div className={styles.card}>
            <p>API_URL: {process.env.API_URL}</p>
          </div>
          <div className={styles.card}>
            <p>BASE_URL: {process.env.BASE_URL}</p>
          </div>
          <div className={styles.card}>
            <p>APP_ENV: {process.env.APP_ENV}</p>
          </div>
        </div>

        <b>ENV NEXT_PUBLIC</b>
        <div className={styles.grid}>
          <div className={styles.card}>
            <p>NEXT_PUBLIC_API_URL: {process.env.NEXT_PUBLIC_API_URL}</p>
          </div>
          <div className={styles.card}>
            <p>NEXT_PUBLIC_APP_ENV: {process.env.NEXT_PUBLIC_APP_ENV}</p>
          </div>
          <div className={styles.card}>
            <p>NEXT_PUBLIC_BASE_URL: {process.env.NEXT_PUBLIC_BASE_URL}</p>
          </div>
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
